### ISSUE TITLE
Sessions folder does not exist

### ISSUE THREAD

**Issue by gcleaves** [sebknoth/alpine-nginx-php7#2]
Hi. I've found that the sessions folder defined by the default php.ini does not exist, and of course is not writable by the nginx 
user. I've created a pull request (first time ever): https://github.com/sebknoth/alpine-nginx-php7/pull/1

**Comment by sfaujour** [comment]
Hey :)
thanks for the issue, i already merged your request.

I'm happy that some one uses my image ^^ (first time ever?!) :D

**Comment by gcleaves** [comment]
I chose your image over others because I see that it is fairly active. But the "edge" tag on the Dockerhub makes for nerves ;).

**Comment by sfaujour** [comment]
hahaha i'll will add the latest tag if you want? ;)

**Comment by gcleaves** [comment]
Well... maybe more people would use your images because the standard `docker pull shito/alpine-nginx-php7` fails with message `latest tag not found` !!! ;) ;) I see you already added the tag.

**Comment by sfaujour** [comment]
yes, that's from a time where kubernetes couldn't update an image, when the tag was "latest". Then i decided to take the alpine tag "edge", never thought about it to add latest again.
