### ISSUE TITLE
UTF character snuck into Dockerfile

### ISSUE THREAD

**Issue by gcleaves** [sebknoth/alpine-nginx-php7#3]
Somehow a UTF symbol found its way into the Dockerfile:

`RUN chown nginx:nginx /var/lib/php7/sessionsÅ`

**Comment by sfaujour** [comment]
Removed in [https://github.com/sebknoth/alpine-nginx-php7/commit/3ec547fd686c8ee7d6249a72184bbc5d0ec718e6](https://github.com/sebknoth/alpine-nginx-php7/commit/3ec547fd686c8ee7d6249a72184bbc5d0ec718e6)
